### PR TITLE
Smashing Magazine - Heat Map Staging

### PR DESCRIPTION
**Pull request by hatemsweileh**
Review our code if you please, we worked on it by doing UX Heat map for the original website [Smashing Magazine](https://www.smashingmagazine.com/), and we did it as below:

- Using the Gray-scale colors
- Using Lorem Ipsum as content
- Using 3 Google Fonts on the website
- Adding some CSS animation for some boxes
- Did a shadow for some boxes and some drawings by using Pseudo Elements
- Using shapes and blocks instead of images
- Using flex, grid, block, and inline-block as a display for the website blocks

**Please view the screenshot below:**
screenshot

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello Team 👋

Good job on this project. 👏👌


 However, kindly make the following adjustments: 

- [x] Required - There are 49 errors that exist on your HTML code. Kindly check them with this [tool](https://validator.w3.org/nu/#file) and fix them.

- [x] Required - According to the Odin requirement. This project is expected to consist of shades of gray, however, there are completely `black` backgrounds. Please correct this and also ensure that the shades of gray you use represent the visual hierarchy on the page.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by mikenath223** [comment]
Refer to this Screenshot from the Odin requirement.

ice_screenshot_20200415-013516

**Comment by lekegitrepo** [comment]
### Hi @hatemswaileh and @taiwocoker 💯 🥇 
### The page looks great. You have done an excellent job here. This is project is approved.

### Reviewed by Temitayo Adeleke.

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved.

**Pull request merged**
